"""Interface for network (for testing)"""

# pylint: disable=R0903

from typing import Protocol
from app.network.structs import Blip, Target


class DoubleSender(Protocol):
    def send(self, val: float) -> None: ...


class BlipSender(Protocol):
    def send(self, val: list[Blip]) -> None: ...


class TargetSender(Protocol):
    def send(self, val: list[Target]) -> None: ...


class Network(Protocol):
    def calibrate(self) -> bool: ...
    def flush(self) -> None: ...
    def get_double_sender(self, leaf: str) -> DoubleSender: ...
    def get_blip_sender(self) -> BlipSender: ...
    def get_target_sender(self) -> TargetSender: ...
    def server_time(self, localtime: int) -> int: ...
